version: "3.6"

services:
  chan-backend:
    container_name: backend
    build: ./
    command: npm run dev
    working_dir: /usr/src/chan-server
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/chan-server
      - /usr/src/chan-server/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    #build: ./config/
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis
    env_file:
      - ./.env
    ports:
      - "6379:6379"
